apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: guestbook
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/guestbook`)
      services:
        - name: guestbook-ui
          port: 8008