#cloud-config

# Update/Upgrade, Reboot if required
package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  # General security
  - ufw
  - unattended-upgrades

# Disable root access
disable_root: true

# Set Locale
locale: en_US.UTF-8
timezone: Europe/London

users:
  - default
  - name: ${username}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    ssh_import_id: None
    lock_passwd: true
    ssh_authorized_keys:
      - "${sshkey-admin}"
    shell: /bin/bash

write_files:
- owner: root:root
  path: /etc/ssh/sshd_config
  permissions: '0644'
  content: |
    # This file was inserted via cloud-init.yaml

    # Authentication:
    PermitRootLogin no
    MaxAuthTries 2
    MaxSessions 3

    PasswordAuthentication no
    PermitEmptyPasswords no

    ChallengeResponseAuthentication no

    UsePAM yes

    AllowAgentForwarding no
    AllowTcpForwarding no
    X11Forwarding no
    PrintMotd no
    TCPKeepAlive no

    Protocol 2
    AllowUsers ${username}
  
- owner: root:root
  path: /etc/rancher/k3s/config.yml
  permissions: '0644'
  content: |
    disable: traefik

runcmd:
  # Delete passwords
  - passwd -d root
  # Restart services
  - service ssh restart
  # UFW
  - echo "Setting up ufw.."
  - ufw default allow outgoing
  - ufw default deny incoming
  - ufw allow ssh
  - ufw allow from 10.0.10.0/24
  - ufw disable
  - ufw enable
  # setup k3s
  - sleep 120
  - curl -sfL https://get.k3s.io | K3S_TOKEN="${k3s_token}" sh -s - server --server https://${master_ip}:6443 --advertise-address ${private_ip} --node-ip ${private_ip}
  # done!
  - echo "Done."
  - touch /cloud-init-ran

final_message: "The system is up after $UPTIME seconds"